### ISSUE TITLE
suggestion: add option to output as $params

### ISSUE THREAD

**Issue by rwu2359** [ryng64/encodeFM#11]
love the new version, want to hack it put the semicolons back at the ends of lines (but that is just personal preference!!)

But I did wonder about the ability (option) to swap out the supplied values for $vars starting with $a, $b etc... Or in fact just the same value so I could do an easy REGEX on it to modify the block how I might want.
I frequently assemble all the required variables during a script from data and then the last step is to assemble the JSON object.

The way FileMaker handle double clicks to select is not something I love a great deal and this could speed up modification and implementation

thankd

**Comment by ryng64** [comment]
hi @rwu2359 
Thanks for the feedback! I agree about the semicolons, I much prefer the look of semicolons on the end. However, I'm split on it because it is nice to manipulate the JSON expression later without worrying about the semicolon arrangement as much. 

My compromise I think is to have a toggle for Leading/ending ";" as I've gotten mixed reviews about this syntax before. 

As far as the ability to swap values for $vars, I had this feature in mind but wasn't sure how to make it make sense in UI. I think I can put another toggle for Use Values/Use Vars.

With an all-or-nothing approach, I could get this type of feature probably done sooner so it is all $vars or all values (as it is now ). I do want to explore the ability to mix values and $vars ( and maybe field references)  down the road though!

**Comment by ryng64** [comment]
- [ ] create semi colon preference toggle
- [ ] use $vars toggle

**Comment by ryng64** [comment]
I've updated app to a new version that includes both using $vars and setting a preference of leading or trailing ";" #12 #14

**Comment by rwu2359** [comment]
Thanks @ryng64 

Downloaded new version, but two sample buttons feed the left pane but the right does not auto-fill with code.

Thanks for including the suggestions though. John R

**Comment by ryng64** [comment]
oh! sorry to hear that! Which version of FM are you using? I may have added features that only work in 19 that could be causing this issue.

Does it still translate at all or is it completely broken?

**Comment by rwu2359** [comment]
its 19.3.2, on Catalina

The previous recent release works fine...
When you click the button to populate with sample data nothing is appearing in the right pane

**Comment by ryng64** [comment]
Thanks! I'm running into an issue on mac where the FileMaker.PerformScript() isn't available yet when a function is called. for now I've stubbed in some default preferences to prevent the issue your describing. Will take a look at making a more stable fix to use saved preferences soon.

**Comment by rwu2359** [comment]
That latest build is working....
I think that's one of the issues around using JS in the wv in FileMaker - the object not being ready in a consistent way

**Comment by rwu2359** [comment]
Have you seen the recent release from Steph (also a P+G person)
https://github.com/stephancasas/onfmready.js

**Comment by ryng64** [comment]
Thanks for the Tip! I've added this to fix the FileMaker{} to be available on ready. #18

**Comment by ryng64** [comment]
Will close for now, new version released with the fixed merged in.
